export const TYPES = [
  { name: 'normal', label: 'ノーマル' },
  { name: 'fire', label: 'ほのお' },
  { name: 'water', label: 'みず' },
  { name: 'electric', label: 'でんき' },
  { name: 'grass', label: 'くさ' },
  { name: 'ice', label: 'こおり' },
  { name: 'fighting', label: 'かくとう' },
  { name: 'poison', label: 'どく' },
  { name: 'ground', label: 'じめん' },
  { name: 'flying', label: 'ひこう' },
  { name: 'psychic', label: 'エスパー' },
  { name: 'bug', label: 'むし' },
  { name: 'rock', label: 'いわ' },
  { name: 'ghost', label: 'ゴースト' },
  { name: 'dragon', label: 'ドラゴン' },
  { name: 'dark', label: 'あく' },
  { name: 'steel', label: 'はがね' },
  { name: 'fairy', label: 'フェアリー' },
];
